config/routes.rb
IppDemo::Application.routes.draw do
  get "company/show"

  post  "login" => "user_sessions#create"
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  
  post  "signup" => "users#create"
  match "signup" => "users#new", :as => :signup
  match "account" => "users#show", :as => :account
  match "account/disconnect" => "users#cancel", :as => :users_cancel
  
  match "intuit/connect" => "intuit#connect", :as => :intuit_connect
  match "intuit/callback" => "intuit#callback", :as => :intuit_callback
  match "intuit/disconnect" => "intuit#disconnect", :as => :intuit_disconnect
  match "intuit/proxy" => "intuit#proxy", :as => :intuit_menu_proxy
  match "intuit/config" => "intuit#oauth_config"
  match "intuit/status" => "intuit#oauth_status"


  match "companies" => "company#index"  
  match "company/:id" => "company#show", :as => :company
  match "company/:id/proxy" => "company#proxy", :as => :company_proxy
  match "company/:id/customers" => "company#customers", :as => :company_customers
  match "company/:id/disconnect" => "company#disconnect", :as => :company_disconnect
  match "company/:id/reconnect" => "company#reconnect", :as => :company_reconnect

  root :to => "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :companies
  has_many :owned_companies, :class_name => "Company", :foreign_key => "owner_id"

  acts_as_authentic do |c|
    crypto_provider = Authlogic::CryptoProviders::BCrypt
  end
  
  validates_presence_of :first_name, :last_name  

  def name
    return [first_name, last_name].join(" ")
  end
  
  def connected_to_intuit?
    # binding.pry
    intuit_access_token? && intuit_access_secret?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'login'
  before_filter :login_required, :only => [:show]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_back_or_default root_path, :notice => "Welcome #{@user.first_name}!"
    else
      render :action => :new
    end
  end
  
  def show
    @user = current_user
    render :layout => "application"
  end
  
  def cancel
    render :layout => "application"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cancel.html.erb
<h2>Sure you wan't to disconnect from Intuit?</h2>
<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>

<%= link_to "&laquo; Go back".html_safe, account_path, :class => "button large", :id => 'cancel-link' %>
<span style="float: right;">
  <%= link_to "Disconnect", intuit_disconnect_path, :class => "button large", :id => 'disconnect-link' %>
</span>

app/views/users/new.html.erb
<%= semantic_form_for @user, :url => signup_path do |form| %>
  <%= form.inputs do %>
    <%= form.input :first_name %>
    <%= form.input :last_name %>
    <%= form.input :email %>
    <%= form.input :password %>
    <%= form.input :password_confirmation, :label => "Confirmation" %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button "Register" %>
  <% end %>
<% end %>

<div id="alternate-link">Already have an account? <%= link_to "Login now!", login_path, :class => "button", :id => 'login-link' %></div>

app/views/users/show.html.erb
<%- if current_user.connected_to_intuit? -%>
Your account has been connected to Intuit!<br />Want to <%= link_to "disconnect your account?", users_cancel_path, :class => "button", :id => 'disconnect-link' %>
<%- else -%>
<ipp:connectToIntuit GrantURL="<%= intuit_connect_url %>"></ipp:connectToIntuit>
<br />
<%- end -%>