config/routes.rb
IppDemo::Application.routes.draw do
  get "company/show"

  post  "login" => "user_sessions#create"
  match "login" => "user_sessions#new", :as => :login
  match "logout" => "user_sessions#destroy", :as => :logout
  
  post  "signup" => "users#create"
  match "signup" => "users#new", :as => :signup
  match "account" => "users#show", :as => :account
  match "account/disconnect" => "users#cancel", :as => :users_cancel
  
  match "intuit/connect" => "intuit#connect", :as => :intuit_connect
  match "intuit/callback" => "intuit#callback", :as => :intuit_callback
  match "intuit/disconnect" => "intuit#disconnect", :as => :intuit_disconnect
  match "intuit/proxy" => "intuit#proxy", :as => :intuit_menu_proxy
  match "intuit/config" => "intuit#oauth_config"
  match "intuit/status" => "intuit#oauth_status"


  match "companies" => "company#index"  
  match "company/:id" => "company#show", :as => :company
  match "company/:id/proxy" => "company#proxy", :as => :company_proxy
  match "company/:id/customers" => "company#customers", :as => :company_customers
  match "company/:id/disconnect" => "company#disconnect", :as => :company_disconnect
  match "company/:id/reconnect" => "company#reconnect", :as => :company_reconnect

  root :to => "home#index"
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :owner, :class_name => "User"
  has_and_belongs_to_many :users

  def intuit_token
    binding.pry
    @intuit_oauth_access_token = OAuth::AccessToken.new(
      Intuit::API.get_consumer(AppConfig["intuit_consumer_key"], AppConfig["intuit_consumer_secret"]),
      intuit_access_token,
      intuit_access_secret
    )
  end

  def connected_to_intuit?
    binding.pry
    return intuit_access_token && intuit_access_secret
  end

  def ever_connected_to_intuit?
    return realm?
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  before_filter :find_company, :except => [:index]

  def index
    @companies = Company.all
  end

  def show
    @render_blue_dot = @company.connected_to_intuit?
    @blue_dot_url = company_proxy_path(@company)
    render :layout => false
  end

  def proxy
    response = @company.intuit_token.get("https://appcenter.intuit.com/api/v1/Account/AppMenu")
    status = response.code
    body = response.body
    render :text => body, :status => status
  end

  def disconnect
    if(@company.connected_to_intuit?)
      @company.intuit_token.get("https://appcenter.intuit.com/api/v1/Connection/Disconnect")
      @company.update_attributes(
        :intuit_access_token => nil,
        :intuit_access_secret => nil
      )
    end
    redirect_to company_path(@company)
  end

  def customers
    binding.pry
    if($redis.exists("intuit:ipp:customers:#{@company.id}"))
      @customers = Crack::XML.parse($redis.get("intuit:ipp:customers:#{@company.id}"))
      @customers ||= {}
      if(@customers["RestResponse"])
        @customers = @customers["RestResponse"]["Customers"]
      end
    else
      binding.pry
      e = @company.intuit_token.get("https://services.intuit.com/sb/customer/v2/#{@company.realm}")
      body = e.body
      $redis.set("intuit:ipp:customers:#{@company.id}", body)
      b = Crack::XML.parse(body)
      @customers = b["RestResponse"]["Customers"] || {}
    end
    @final = []
    if(@customers["Customer"])
      @customers["Customer"].each do |c|
        next unless c["Address"] && c["Address"]["Line1"] && c["Address"]["Line2"]
        if($redis.exists("intuit:ipp:anywhere:company:#{@company.id}:customers:#{c["Id"]}:location"))
          c["Geolocation"] = Crack::JSON.parse($redis.get("intuit:ipp:anywhere:company:#{@company.id}:customers:#{c["Id"]}:location"))
        else
          r = Crack::JSON.parse(HTTParty.get("http://maps.googleapis.com/maps/api/geocode/json", :query => { :sensor => false, :address => [c["Address"]["Line2"], c["Address"]["City"],
c["Address"]["CountrySubDivisionCode"], c["Address"]["PostalCode"]].join(" ") }).body)
          if(r["results"] && r["results"][0] && r["results"][0]["geometry"] && r["results"][0]["geometry"]["location"])
            r = r["results"][0]["geometry"]["location"]
            $redis.set("intuit:ipp:anywhere:company:#{@company.id}:customers:#{c["Id"]}:location", r.to_json)
            c["Geolocation"] = r
          end
        end
        if(c["Geolocation"])
          @final << c
        end
      end
    end
    render :json => @final
  end

  def reconnect
    render :layout => false
  end

  private
   def find_company
     @company = Company.find(params[:id])
   end


end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/index.html.erb
<table style="width: 100%; text-align: left;">
  <thead><tr>
    <th>Company</th>
    <th>Realm</th>
    <th>Owner</th>
    <th>Owner Email</th>
  </tr></thead>
  <tbody>
<% @companies.each do |c| %>
    <tr>
      <td><%= link_to c.name, company_path(c) %></td>
      <td><%= c.realm %></td>
      <td><%= c.owner.first_name + " " + c.owner.last_name %></td>
      <td><%= c.owner.email %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/company/reconnect.html.erb
  <ipp:reconnectToIntuit></ipp:reconnectToIntuit>
  <script src="https://qblab-ipp-v2r18.intuit.com/Content/IA/intuit.ipp.anywhere-0.0.0.js" type="text/javascript"></script> 
  <script type="text/javascript"> 
    intuit.ipp.anywhere.setup({
      menuProxy: '',
      grantUrl: '<%= intuit_connect_url %>'
    });
  </script> 

app/views/company/show.html.erb
<!DOCTYPE html>
<html xmlns="https://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:ipp="">
<head>
  <title>IppDemo</title>
  <%= include_stylesheets :app %>
  <%= include_javascripts :app %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <script type="text/javascript"
    src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <script type="text/javascript">
    var map, infoWindow;
    function initialize() {
      var latlng = new google.maps.LatLng(37.231, -122.0458);
      var myOptions = {
        zoom: 8,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      };
      map = new google.maps.Map(document.getElementById("map_canvas"),
          myOptions);
      infoWindow = new google.maps.InfoWindow({
        content: ""
      });

    }
  </script>
</head>
<body onload="initialize()">
  <% if @render_blue_dot %><ipp:blueDot></ipp:blueDot><% end %>
  <div style="position: fixed; width: 100%; height: 100%;"><div id="map_canvas" style="position: fixed;"></div></div>
  <div id="maps-container"<%= ' style="display: none' if @hide_body %>>
    <div id="maps-header">
      <h1><%= link_to "Customer.com", root_path %></h1>
      <span id="nav-menu">
        <%= link_to "my account", account_path, :id => 'my-account-link' %> | <%= link_to "logout", logout_path, :link => 'logout-link' %>
      </span>
    </div>
    <h2><%= @company.name %></h2>
    <div id="loaded-content">
      <% if @company.connected_to_intuit? %>
      <img src="/images/loading.gif" style="display: block; margin: 0 auto;" />
      <% end %>
    </div>
    <% if @company.connected_to_intuit? %>
      <%= link_to "Disconnect this company?", company_disconnect_path(@company), :class => "button", :id => 'disconnect-link' %><br />
    <% else %>
      <ipp:connectToIntuit></ipp:connectToIntuit>
    <% end %>
  </div>
  <script src="https://js.appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js" type="text/javascript"></script>
  <script type="text/javascript">
    intuit.ipp.anywhere.setup({
      menuProxy: '<%= @blue_dot_url %>',
      grantUrl: '<%= intuit_connect_url %>'
    });
    <% if @company.connected_to_intuit? %>
    $(function () {
      $.ajax({
        url: '<%= company_customers_path(@company) %>',
        success: function (data) {
          $("#loaded-content").html("");
          $.each(data, function (index, obj) {
            m = new google.maps.Marker({
              position: new google.maps.LatLng(obj.Geolocation.lat, obj.Geolocation.lng), 
              map: map
            });
            m.html = obj.Name + "<br />";
            if(obj.Address.Line2) {
              m.html += obj.Address.Line2 + "<br />";
            }
            if(obj.Address.Line3) {
              m.html += obj.Address.Line3 + "<br />";
            }
            if(obj.Address.Line4) {
              m.html += obj.Address.Line4 + "<br />";
            }
            if(obj.Address.City) {
              m.html += obj.Address.City + ", ";
            }
            if(obj.Address.CountrySubDivisionCode) {
              m.html += obj.Address.CountrySubDivisionCode + " ";
            }
            if(obj.Address.PostalCode) {
              m.html += obj.Address.PostalCode;
            }
            m.html += "<br /><br />";
            if(obj.Email && obj.Email.Address) {
              m.html += obj.Email.Address + "<br />";
            }
            if(obj.Phone && obj.Phone.FreeFormNumber) {
              m.html += obj.Phone.FreeFormNumber + "<br />";
            }
            google.maps.event.addListener(m, 'click', function() { infoWindow.setContent(this.html); infoWindow.open(map,this); });
          });
        },
        error: function () {
          $("#loaded-content").html("<span style='color: red;'>We are sorry, but your customer data cannot be loaded</span>");
        }
      });
    });
    <% end %>
  </script>
</body>
</html>